# Intentionally vulnerable K8s manifest for supSec demo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      containers:
        - name: app
          image: myapp
          securityContext:
            privileged: true
            runAsUser: 0
